export {
  formatDSCodeError,
  runDSCode,
  runDSCodeProcess,
} from "./cli-runtime.js";
export { createDSCodeExtension } from "./dscode-extension.js";
export {
  createDSCodeRpcClient,
  getDSCodeRpcEntryPath,
  RpcClient,
  type DSCodeRpcClientOptions,
  type RpcClientOptions,
} from "./rpc-client.js";
export {
  authenticateProvider,
  getDSCodeAgentDir,
  getDSCodeAuthPath,
  hasDeepSeekEnvironmentKey,
  hasStoredDeepSeekKey,
  hasStoredProviderCredential,
  removeStoredDeepSeekKey,
  removeStoredProviderCredential,
  runAuthCommand,
  saveDeepSeekKey,
  saveProviderApiKey,
  validateDeepSeekKey,
  type ApiKeyProviderId,
  type KeyValidation,
  type ProviderLoginResult,
} from "./auth.js";
export type { AuthEvent, AuthInteraction, AuthPrompt } from "@earendil-works/pi-ai";
export {
  createDSCodeCredentialStore,
  FileCredentialStore,
  installDSCodeCredentialStore,
  KeyringCredentialStore,
  type CreateCredentialStoreOptions,
  type DSCodeKeyringFactory,
} from "./credential-store.js";
export {
  getDSCodeArchivedSessionsDir,
  getDSCodeHome,
  getDSCodeSessionsDir,
  getDSCodeTracesDir,
  initializeDSCodeHome,
  migrateLegacyDSCodeHome,
  partitionExistingSessions,
  partitionSessionFile,
  type PartitionedSessionPath,
} from "./home.js";
export {
  DSCodeStateStore,
  getDSCodeStatePath,
  indexDSCodeSession,
  listDSCodeThreads,
  type DSCodeThread,
  type ListThreadOptions,
} from "./state.js";
export {
  DEFAULT_DEEPSEEK_BASE_URL,
  getDSCodeStorageSettings,
  getDSCodeSettingsPath,
  getStoredDeepSeekBaseUrl,
  normalizeDeepSeekBaseUrl,
  saveDeepSeekBaseUrl,
  type CredentialStoreMode,
  type DSCodeStorageSettings,
  type HistoryPersistence,
} from "./settings.js";
export {
  MODEL_CREDENTIAL_ENV_KEYS,
  SUPPORTED_PROVIDER_IDS,
  defaultEffortForProvider,
  defaultModelForProvider,
  getStoredModelSelection,
  isSupportedProviderId,
  parseSupportedProviderId,
  providerDisplayName,
  providerEnvironmentKey,
  stripModelCredentialEnvironment,
  type StoredModelSelection,
  type SupportedProviderId,
} from "./providers.js";
export {
  parseRuntimeArgs,
  printDSCodeHelp,
  sandboxModeSchema,
  type DSCodeRuntimeOptions,
  type ParsedRuntimeArgs,
  type SandboxMode,
} from "./runtime-options.js";
export {
  classifyRoute,
  createRoutePhaseState,
  createRouteState,
  formatRoutePhaseStatus,
  formatRouteStatus,
  isOpeningRouteTurn,
  latestUserMessageText,
  parseRouteSelection,
  restoreRoutePhaseState,
  restoreRouteState,
  routeCommandUsage,
  routePhaseTraceAttributes,
  routeProfileLabel,
  routeProfileShortLabel,
  routeStateTraceAttributes,
  routeSystemPrompt,
  routeThinkingBoost,
  routeThinkingTarget,
  ROUTE_PROFILE_IDS,
  ROUTE_THINKING_TARGETS,
  ROUTE_PHASE_ENTRY,
  ROUTE_STATE_ENTRY,
  type RoutePhase,
  type RoutePhaseState,
  type RouteProfileId,
  type RouteSelection,
  type RouteSelectionInput,
  type RouteSource,
  type RouteState,
  type RouteThinkingTarget,
} from "./route-profile.js";
export {
  PERSONALIZATION_TONE_IDS,
  buildPersonalizationPrompt,
  composePersonalizedSystemPrompt,
  loadPersonalizationPrompt,
  type PersonalizationPreferences,
  type PersonalizationTone,
} from "./personalization.js";
export { DSCODE_VERSION } from "./version.js";
export {
  AGENT_TRACE_SCHEMA_VERSION,
  AgentRuntimeTrace,
  classifyHttpStatus,
  summarizeContent,
  summarizeValue,
  usageFromPiUsage,
  type AgentRuntimeTraceOptions,
  type AgentTraceError,
  type AgentTraceEvent,
  type AgentTraceEventInput,
  type AgentTraceEventType,
  type AgentTraceStatus,
  type AgentTraceUsage,
  type TraceContentSummary,
  type TraceValueSummary,
} from "./observability.js";
export {
  compareTraceReports,
  formatReplayReport,
  readTraceFile,
  replayTraceLines,
  summarizeTrace,
  type TraceComparison,
  type TraceCounts,
  type TraceReplayReport,
  type TraceUsageSummary,
} from "./replay.js";
export {
  evaluateReplay,
  evaluateTrace,
  evaluateTraceLines,
  formatEvaluationResult,
  type EvaluationOptions,
  type EvaluationResult,
} from "./evaluation.js";
export {
  AGENT_FIXTURE_KIND,
  AGENT_FIXTURE_SCHEMA_VERSION,
  AgentFixtureRecorder,
  AgentFixtureReplay,
  readAgentFixtureFile,
  readAgentFixtureFileSync,
  writeAgentFixture,
  type AgentFixture,
  type AgentFixtureAssertions,
  type AgentFixtureEvaluation,
  type AgentFixtureResponse,
  type FixtureContentBlock,
  type FixtureStopReason,
  type FixtureUsage,
} from "./fixture.js";
